// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MermaidChart
{
    internal sealed partial class Vsix
    {
        public const string Id = "MermaidChart.ff484abd-f4f3-4a6c-9294-9936b1fa74ac";
        public const string Name = "MermaidChart";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
