// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MermaidChart
{
    internal sealed partial class Vsix
    {
        public const string Id = "MermaidChart";
        public const string Name = "Mermaid Chart";
        public const string Description = @"The Mermaid Chart extension for JetBrains IDEs enables developers to view and edit diagrams stored in Mermaid Chart within the IDE. With integration to the Mermaid Chart service, this extension allows users to attach diagrams to their code. Gain quick access to read and edit diagrams.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "MermaidChart";
        public const string Tags = "";
    }
}
