// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MermaidChart
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MermaidChartString = "3cae6b67-bb28-48f6-888f-641fbb567d4a";
        public static Guid MermaidChart = new Guid(MermaidChartString);

        public const string guidMermaidChartPackageCmdSetString = "512fc355-237a-4937-9805-cbdb25e11682";
        public static Guid guidMermaidChartPackageCmdSet = new Guid(guidMermaidChartPackageCmdSetString);

        public const string guidImagesString = "0539ae13-0390-4fb5-a266-96ed3eb9cd16";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string windowImages1String = "eef6e5f7-721b-4283-855a-5dfd714f4e36";
        public static Guid windowImages1 = new Guid(windowImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidCommand1 = 0x0100;
        public const int cmdidToolWindow1Command = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int toolWindowPic1 = 0x0001;
        public const int toolWindowPic2 = 0x0002;
        public const int toolWindowPicSearch = 0x0003;
        public const int toolWindowPicX = 0x0004;
        public const int toolWindowPicArrows = 0x0005;
        public const int toolWindowPicStrikethrough = 0x0006;
    }
}