// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MermaidChart
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MermaidChartString = "3cae6b67-bb28-48f6-888f-641fbb567d4a";
        public static Guid MermaidChart = new Guid(MermaidChartString);

        public const string DiagramListWindowCmdSetString = "c74abe73-65d7-4e96-b2f4-30c8354348ed";
        public static Guid DiagramListWindowCmdSet = new Guid(DiagramListWindowCmdSetString);

        public const string MermaidChartCommandSetString = "512fc355-237a-4937-9805-cbdb25e11682";
        public static Guid MermaidChartCommandSet = new Guid(MermaidChartCommandSetString);

        public const string DiagramListWindowBitmapString = "eef6e5f7-721b-4283-855a-5dfd714f4e36";
        public static Guid DiagramListWindowBitmap = new Guid(DiagramListWindowBitmapString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DiagramListToolbar = 0x1000;
        public const int DiagramListToolbarGroup = 0x1050;
        public const int MyMenuGroup = 0x1020;
        public const int RefreshDiagramList = 0x0100;
        public const int OpenDiagramList = 0x1021;
        public const int DiagramListWindowIcon = 0x0001;
    }
}